### ISSUE TITLE
panic when indexing an hugo site

### ISSUE THREAD

**Issue by jvermillard** [blevesearch/hugoidx#1]
panic: runtime error: invalid memory address or nil pointer dereference

```
[signal 0xb code=0x1 addr=0x98 pc=0x40197f]

goroutine 1 [running]:
main.buildindex()
    /home/jvermillar/go/src/github.com/blevesearch/hugoidx/main.go:68 +0x74f
main.glob.func1(0x13d7960, 0xc820160740, 0x0, 0x1)
    /home/jvermillar/go/src/github.com/blevesearch/hugoidx/main.go:30 +0x19
github.com/spf13/cobra.(*Command).execute(0x13d7960, 0xc82000a370, 0x1, 0x1, 0x0, 0x0)
    /home/jvermillar/go/src/github.com/spf13/cobra/command.go:476 +0x403
github.com/spf13/cobra.(*Command).Execute(0x13d7960, 0x0, 0x0)
    /home/jvermillar/go/src/github.com/spf13/cobra/command.go:550 +0x46a
main.main()
    /home/jvermillar/go/src/github.com/blevesearch/hugoidx/main.go:107 +0x23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82001a180, 0xc82001a1e0)
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 6 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82001a180, 0xc82001a1e0)
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 7 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82001a180, 0xc82001a1e0)
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 8 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82001a180, 0xc82001a1e0)
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
    /home/jvermillar/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2
```

**Comment by mschoch** [comment]
Was any other output printed to console before the crash?  Did it say Opening or Creating the index?

The line of the crash is here:

https://github.com/blevesearch/hugoidx/blob/master/main.go#L68

Also, which version of hugo are you using?  It doesn't seem likely but it could be related.

**Comment by steveyen** [comment]
Took a peek, and one thought is that maybe the jww.FATAL.Printf() call above isn't really fatal (does not exit the program as perhaps expected, but instead continues onwards)...

```
https://github.com/blevesearch/hugoidx/blob/master/main.go#L50
```

From a quick peek at the jww implementation, I couldn't exactly tell what FATAL was doing.

**Comment by mschoch** [comment]
OK, I've reproduce the problem.  It is one we found/fixed the other day, but hadn't pushed yet.  The problem was introduced when I made the "index type" configurable.  I had intended the change to be backwards compatible, but I messed that up.

When running hugoidx with current code, but opening an index built with slightly older code you get:

```
FATAL: 2015/09/25 error creating/opening index: unknown index type
```

logged just before the panic.

Let me move the fix over to master and push.

**Comment by mschoch** [comment]
Please pull latest bleve and hugoidx, I believe the problem is fixed with:

https://github.com/blevesearch/hugoidx/commit/ad19a582eb8ecc2417c8bf0fb058da1d8294cba0
https://github.com/blevesearch/bleve/commit/1c9feaf792cea1a1171951657af58f8effeff3db

**Comment by jvermillard** [comment]
works now! thanks
